# Imported Required Libraries:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [17]:
from sklearn.metrics import mean_squared_error,r2_score,explained_variance_score

# Loaded Training Data:

In [4]:
train_data = pd.read_csv('D:\\ML\\DL Repo\\JOB-A-THON - January 2023\\train_BRCpofr.csv')

# Checking Training Data (Column names and it's values)

In [5]:
train_data.head()

gender  area  qualification  income  marital_status  vintage  claim_amount  \
0       0     1              2       2               1        5          5790   
1       0     0              1       2               0        8          5080   
2       0     1              2       2               1        8          2599   
3       1     0              1       2               0        7             0   
4       0     1              1       3               1        6          3508   

   num_policies  policy  type_of_policy    cltv  
0             2       2               2   64308  
1             2       2               2  515400  
2             2       2               2   64212  
3             2       2               2   97920  
4             2       2               1   59736

# Created valriable to store input data column names:

In [3]:
train_columns = list(['gender','area','qualification','income','marital_status','vintage','claim_amount','num_policies','policy','type_of_policy'])

# Spliting training data to use for both training & validating the model:

In [6]:
X_train,X_test,Y_train,Y_test = train_test_split(train_data[train_columns],train_data['cltv'],test_size = 0.3,random_state = 1)

# Scaling input data (claim_amount):

In [7]:
X_mms = MinMaxScaler()
claim_amount_train = X_mms.fit_transform(np.array(X_train['claim_amount']).reshape(-1,1))
claim_amount_test = X_mms.transform(np.array(X_test['claim_amount']).reshape(-1,1))
claim_amount_train[:5]

array([[0.16965573],
       [0.09054995],
       [0.11202734],
       [0.        ],
       [0.        ]])

# Scaling target data (cltv):

In [8]:
Y_mms = MinMaxScaler()
cltv_train = Y_mms.fit_transform(np.array(Y_train).reshape(-1,1))
cltv__test = Y_mms.transform(np.array(Y_test).reshape(-1,1))
cltv_train[:5]

array([[0.44769178],
       [0.6371203 ],
       [0.05677021],
       [0.02871117],
       [0.01211601]])

# Training variables are updated as per scaled data:

In [9]:
X_train['claim_amount'] = claim_amount_train
X_test['claim_amount'] = claim_amount_test
Y_train = cltv_train
Y_test = cltv__test

In [14]:
Y_train.shape

(62574, 1)

# Converting all data into numpy array:

In [11]:
X_train_np,X_test_np,Y_train_np,Y_test_np = np.array(X_train),np.array(X_test),Y_train,Y_test

# Model Creation:

In [12]:
model = GradientBoostingRegressor()

# Model trainging:

In [13]:
model.fit(X_train_np,Y_train_np)

D:\Anaconda\envs\GPU\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor()

# Model Prediction on vaidation data:

In [15]:
 y_pred = model.predict(X_test_np)

# Calculating model performance variable:

In [18]:
explained_variance_score(Y_test_np, y_pred)

0.16035911745448583

In [19]:
mean_squared_error(Y_test_np, y_pred)

0.013802224283127773

In [20]:
r2_score(Y_test_np, y_pred)

0.16034366406979583

# Loaded Test Data:

In [21]:
test_data = pd.read_csv('D:\\ML\\DL Repo\\JOB-A-THON - January 2023\\test_koRSKBP.csv')

# Creation/export Submission data

In [22]:
test_data.head()

id  gender  area  qualification  income  marital_status  vintage  \
0  89393       1     0              1       2               0        6   
1  89394       1     1              1       1               0        4   
2  89395       0     0              1       2               1        7   
3  89396       1     0              2       3               1        2   
4  89397       1     1              1       1               0        5   

   claim_amount  num_policies  policy  type_of_policy  
0          2134             2       1               0  
1          4102             2       2               2  
2          2925             2       1               1  
3             0             2       1               0  
4         14059             2       1               0

In [23]:
ca = X_mms.transform(np.array(test_data['claim_amount']).reshape(-1,1))
ca[:5]

array([[0.06690914],
       [0.12861353],
       [0.09171004],
       [0.        ],
       [0.44080391]])

In [24]:
test_data['claim_amount'] = ca
test_data.head()

id  gender  area  qualification  income  marital_status  vintage  \
0  89393       1     0              1       2               0        6   
1  89394       1     1              1       1               0        4   
2  89395       0     0              1       2               1        7   
3  89396       1     0              2       3               1        2   
4  89397       1     1              1       1               0        5   

   claim_amount  num_policies  policy  type_of_policy  
0      0.066909             2       1               0  
1      0.128614             2       2               2  
2      0.091710             2       1               1  
3      0.000000             2       1               0  
4      0.440804             2       1               0

In [27]:
y_pred = model.predict(np.array(test_data[train_columns]))
y_pred[:5]

array([0.10107732, 0.14739056, 0.09645678, 0.09093685, 0.15535375])

In [29]:
y_pred_actual = Y_mms.inverse_transform(y_pred.reshape(-1,1))
y_pred_actual[:5]

array([[ 95505.3072386 ],
       [127889.37513804],
       [ 92274.43806097],
       [ 88414.68482123],
       [133457.55655678]])

In [34]:
test_result = pd.DataFrame([test_data['id'].squeeze(),np.squeeze(y_pred_actual)]).T


In [35]:
test_result = test_result.rename(columns={'Unnamed 0':'cltv'})
test_result.head()

id           cltv
0  89393.0   95505.307239
1  89394.0  127889.375138
2  89395.0   92274.438061
3  89396.0   88414.684821
4  89397.0  133457.556557

In [36]:
test_result.to_csv('D:\\ML\\DL Repo\\JOB-A-THON - January 2023\\test_result_GBR.csv',index=False)